//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessObjects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конструктор с параметрами не поддерживается.
        /// </summary>
        internal static string ConstructorsWithParametersNotSupported {
            get {
                return ResourceManager.GetString("ConstructorsWithParametersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конструктор по умолчанию.
        /// </summary>
        internal static string DefaultConstructor {
            get {
                return ResourceManager.GetString("DefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C {0} по {1}.
        /// </summary>
        internal static string FORMAT_PERIODCUSTOM {
            get {
                return ResourceManager.GetString("FORMAT_PERIODCUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} года.
        /// </summary>
        internal static string FORMAT_PERIODMONTH {
            get {
                return ResourceManager.GetString("FORMAT_PERIODMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} {2} года.
        /// </summary>
        internal static string FORMAT_PERIODMONTHRANGE {
            get {
                return ResourceManager.GetString("FORMAT_PERIODMONTHRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-й квартал {1} года.
        /// </summary>
        internal static string FORMAT_PERIODQARTAL {
            get {
                return ResourceManager.GetString("FORMAT_PERIODQARTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все данные за {0} год.
        /// </summary>
        internal static string FORMAT_PERIODYEAR {
            get {
                return ResourceManager.GetString("FORMAT_PERIODYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено свойство.
        /// </summary>
        internal static string MemberNotFoundException {
            get {
                return ResourceManager.GetString("MemberNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод не реализован.
        /// </summary>
        internal static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойство приватное.
        /// </summary>
        internal static string PropertyIsPrivateField {
            get {
                return ResourceManager.GetString("PropertyIsPrivateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойство не зарегестрировано.
        /// </summary>
        internal static string PropertyNotRegistered {
            get {
                return ResourceManager.GetString("PropertyNotRegistered", resourceCulture);
            }
        }
    }
}
