//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessObjects.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить в корзину|Удалить|Исключить|Запретить использование.
        /// </summary>
        internal static string ACTION_DELETE {
            get {
                return ResourceManager.GetString("ACTION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        internal static string ACTION_TYPED_DEL {
            get {
                return ResourceManager.GetString("ACTION_TYPED_DEL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CREATE_X16 {
            get {
                object obj = ResourceManager.GetObject("CREATE_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CREATE_X32 {
            get {
                object obj = ResourceManager.GetObject("CREATE_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DATABASE_X16 {
            get {
                object obj = ResourceManager.GetObject("DATABASE_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELETE_X16 {
            get {
                object obj = ResourceManager.GetObject("DELETE_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DOCUMENTDONE_X16 {
            get {
                object obj = ResourceManager.GetObject("DOCUMENTDONE_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EDIT_X32 {
            get {
                object obj = ResourceManager.GetObject("EDIT_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXIT_X32 {
            get {
                object obj = ResourceManager.GetObject("EXIT_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FOLDER_X32 {
            get {
                object obj = ResourceManager.GetObject("FOLDER_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FOLDEROPEN_X16 {
            get {
                object obj = ResourceManager.GetObject("FOLDEROPEN_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HELP_X32 {
            get {
                object obj = ResourceManager.GetObject("HELP_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HIERARCHYFIND_X16 {
            get {
                object obj = ResourceManager.GetObject("HIERARCHYFIND_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HISTORY_X16 {
            get {
                object obj = ResourceManager.GetObject("HISTORY_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При удалении в \&quot;Корзину\&quot; возможно полное востановление, а при полном удалении дальнейшее востановление невозможно. Рекомендуется использовать удаление в корзину, использовать полное удаление возможно только при полной уверенности в правильности своих действий..
        /// </summary>
        internal static string INFO_DELETEELEMENT {
            get {
                return ResourceManager.GetString("INFO_DELETEELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть информацию....
        /// </summary>
        internal static string INFO_VIEW_DETAIL {
            get {
                return ResourceManager.GetString("INFO_VIEW_DETAIL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap KEY_X16 {
            get {
                object obj = ResourceManager.GetObject("KEY_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KEYS_X32 {
            get {
                object obj = ResourceManager.GetObject("KEYS_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предприятие.
        /// </summary>
        internal static string LABEL_COMPANY {
            get {
                return ResourceManager.GetString("LABEL_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад.
        /// </summary>
        internal static string LABEL_STORE {
            get {
                return ResourceManager.GetString("LABEL_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка выполнения действий!.
        /// </summary>
        internal static string MSG_EX_ACTION {
            get {
                return ResourceManager.GetString("MSG_EX_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления!.
        /// </summary>
        internal static string MSG_EX_DELETE {
            get {
                return ResourceManager.GetString("MSG_EX_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колонку нельзя удалить!.
        /// </summary>
        internal static string MSG_EX_DELETECOLUMN {
            get {
                return ResourceManager.GetString("MSG_EX_DELETECOLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления подтипа!.
        /// </summary>
        internal static string MSG_EX_DELETEDBENTITYKIND {
            get {
                return ResourceManager.GetString("MSG_EX_DELETEDBENTITYKIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления типа документа!.
        /// </summary>
        internal static string MSG_EX_DELETEDOCKIND {
            get {
                return ResourceManager.GetString("MSG_EX_DELETEDOCKIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления флага!.
        /// </summary>
        internal static string MSG_EX_DELETEFLAG {
            get {
                return ResourceManager.GetString("MSG_EX_DELETEFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления метода!.
        /// </summary>
        internal static string MSG_EX_DELETEMETHOD {
            get {
                return ResourceManager.GetString("MSG_EX_DELETEMETHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрещается перемещать разные виды иерархий!.
        /// </summary>
        internal static string MSG_EX_MOVE_HIERARCYKINDS {
            get {
                return ResourceManager.GetString("MSG_EX_MOVE_HIERARCYKINDS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NEW_X32 {
            get {
                object obj = ResourceManager.GetObject("NEW_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PERIOD_X16 {
            get {
                object obj = ResourceManager.GetObject("PERIOD_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PERIOD_X32 {
            get {
                object obj = ResourceManager.GetObject("PERIOD_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PREFERENCE_X32 {
            get {
                object obj = ResourceManager.GetObject("PREFERENCE_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PREVIEW_X32 {
            get {
                object obj = ResourceManager.GetObject("PREVIEW_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PRICELIST_X16 {
            get {
                object obj = ResourceManager.GetObject("PRICELIST_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PRINT_X32 {
            get {
                object obj = ResourceManager.GetObject("PRINT_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PROPERTIES_X16 {
            get {
                object obj = ResourceManager.GetObject("PROPERTIES_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap REFRESH_X16 {
            get {
                object obj = ResourceManager.GetObject("REFRESH_X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap REFRESH_X32 {
            get {
                object obj = ResourceManager.GetObject("REFRESH_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAVE_X32 {
            get {
                object obj = ResourceManager.GetObject("SAVE_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAVECLOSE_X32 {
            get {
                object obj = ResourceManager.GetObject("SAVECLOSE_X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетные счета.
        /// </summary>
        internal static string SRT_LABEL_PAGE_BANKACC {
            get {
                return ResourceManager.GetString("SRT_LABEL_PAGE_BANKACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активный|Пассивный|Пассивно-активный|Забалансовый.
        /// </summary>
        internal static string STR_ACCOUNTSALDO {
            get {
                return ResourceManager.GetString("STR_ACCOUNTSALDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернутое|Развернутое|Свернутое по корреспондентам|Свернутое по объектам учета.
        /// </summary>
        internal static string STR_ACCOUNTSUBTYPE {
            get {
                return ResourceManager.GetString("STR_ACCOUNTSUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешения.
        /// </summary>
        internal static string STR_ACL {
            get {
                return ResourceManager.GetString("STR_ACL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string STR_BTN_CANCEL {
            get {
                return ResourceManager.GetString("STR_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string STR_BTN_OK {
            get {
                return ResourceManager.GetString("STR_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить в корзину|Удалить навсегда.
        /// </summary>
        internal static string STR_CHOICE_DEL {
            get {
                return ResourceManager.GetString("STR_CHOICE_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        internal static string STR_CREATENEW {
            get {
                return ResourceManager.GetString("STR_CREATENEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string STR_DATE {
            get {
                return ResourceManager.GetString("STR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string STR_DELETE {
            get {
                return ResourceManager.GetString("STR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор: {1}{0}Номер: {2}{0}Уровень:{3}{0}Состояние: {4}{0}Процедура: {5}{0}Сообщение:{6}.
        /// </summary>
        internal static string STR_ERR_DBE_FORMAT {
            get {
                return ResourceManager.GetString("STR_ERR_DBE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные за период ({0}).
        /// </summary>
        internal static string STR_FACTS_VALUEPERIOD {
            get {
                return ResourceManager.GetString("STR_FACTS_VALUEPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул.
        /// </summary>
        internal static string STR_LABEL_ARTICUL {
            get {
                return ResourceManager.GetString("STR_LABEL_ARTICUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штрихкод.
        /// </summary>
        internal static string STR_LABEL_BARCODE {
            get {
                return ResourceManager.GetString("STR_LABEL_BARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бренд.
        /// </summary>
        internal static string STR_LABEL_BRAND {
            get {
                return ResourceManager.GetString("STR_LABEL_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кат. №.
        /// </summary>
        internal static string STR_LABEL_CATALOGUE {
            get {
                return ResourceManager.GetString("STR_LABEL_CATALOGUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Признак.
        /// </summary>
        internal static string STR_LABEL_CODE {
            get {
                return ResourceManager.GetString("STR_LABEL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колонки.
        /// </summary>
        internal static string STR_LABEL_COLUMNS {
            get {
                return ResourceManager.GetString("STR_LABEL_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма.
        /// </summary>
        internal static string STR_LABEL_FORM {
            get {
                return ResourceManager.GetString("STR_LABEL_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гуид.
        /// </summary>
        internal static string STR_LABEL_GUID {
            get {
                return ResourceManager.GetString("STR_LABEL_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ид.
        /// </summary>
        internal static string STR_LABEL_ID {
            get {
                return ResourceManager.GetString("STR_LABEL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изготовитель.
        /// </summary>
        internal static string STR_LABEL_MANUFACTURER {
            get {
                return ResourceManager.GetString("STR_LABEL_MANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        internal static string STR_LABEL_MEMO {
            get {
                return ResourceManager.GetString("STR_LABEL_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string STR_LABEL_NAME {
            get {
                return ResourceManager.GetString("STR_LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ном №.
        /// </summary>
        internal static string STR_LABEL_NOM {
            get {
                return ResourceManager.GetString("STR_LABEL_NOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связи.
        /// </summary>
        internal static string STR_LABEL_PAGE_LINKS {
            get {
                return ResourceManager.GetString("STR_LABEL_PAGE_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string STR_LABEL_PAGECOMMON {
            get {
                return ResourceManager.GetString("STR_LABEL_PAGECOMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты.
        /// </summary>
        internal static string STR_LABEL_PAGEFACTS {
            get {
                return ResourceManager.GetString("STR_LABEL_PAGEFACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы.
        /// </summary>
        internal static string STR_LABEL_PAGEHIERARCHY {
            get {
                return ResourceManager.GetString("STR_LABEL_PAGEHIERARCHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства.
        /// </summary>
        internal static string STR_LABEL_PAGEID {
            get {
                return ResourceManager.GetString("STR_LABEL_PAGEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единицы измерения.
        /// </summary>
        internal static string STR_LABEL_PAGEPRODUNITS {
            get {
                return ResourceManager.GetString("STR_LABEL_PAGEPRODUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояния.
        /// </summary>
        internal static string STR_LABEL_PAGESTATE {
            get {
                return ResourceManager.GetString("STR_LABEL_PAGESTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типоразмер.
        /// </summary>
        internal static string STR_LABEL_SIZE {
            get {
                return ResourceManager.GetString("STR_LABEL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер (в:ш:г).
        /// </summary>
        internal static string STR_LABEL_SIZEWHD {
            get {
                return ResourceManager.GetString("STR_LABEL_SIZEWHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок хранения.
        /// </summary>
        internal static string STR_LABEL_STORAGEPERIOD {
            get {
                return ResourceManager.GetString("STR_LABEL_STORAGEPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон.
        /// </summary>
        internal static string STR_LABEL_TEMPLATE {
            get {
                return ResourceManager.GetString("STR_LABEL_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торговая марка.
        /// </summary>
        internal static string STR_LABEL_TRADEMARK {
            get {
                return ResourceManager.GetString("STR_LABEL_TRADEMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы.
        /// </summary>
        internal static string STR_LABEL_TYPES {
            get {
                return ResourceManager.GetString("STR_LABEL_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ед. измерения.
        /// </summary>
        internal static string STR_LABEL_UNIT {
            get {
                return ResourceManager.GetString("STR_LABEL_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес.
        /// </summary>
        internal static string STR_LABEL_WEIGHT {
            get {
                return ResourceManager.GetString("STR_LABEL_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид цены.
        /// </summary>
        internal static string STR_PRICEKIND {
            get {
                return ResourceManager.GetString("STR_PRICEKIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прайс-лист.
        /// </summary>
        internal static string STR_PRICELIST {
            get {
                return ResourceManager.GetString("STR_PRICELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства.
        /// </summary>
        internal static string STR_PROPERTIES {
            get {
                return ResourceManager.GetString("STR_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Эффективные разрешения.
        /// </summary>
        internal static string STR_RIGHTS_EFFECTIVE {
            get {
                return ResourceManager.GetString("STR_RIGHTS_EFFECTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В корзину.
        /// </summary>
        internal static string STR_TRASH {
            get {
                return ResourceManager.GetString("STR_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;нет данных&gt;.
        /// </summary>
        internal static string STR_TXT_NODATA {
            get {
                return ResourceManager.GetString("STR_TXT_NODATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        internal static string STR_VALUE {
            get {
                return ResourceManager.GetString("STR_VALUE", resourceCulture);
            }
        }
    }
}
