//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.UpdateServices.ServiceUpdate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://docssys.com/biservices", ConfigurationName="ServiceUpdate.IServiceUpdate")]
    public interface IServiceUpdate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/CustomViewLists", ReplyAction="http://docssys.com/biservices/IServiceUpdate/CustomViewListsResponse")]
        BusinessObjects.CustomViewList[] CustomViewLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/CodeNames", ReplyAction="http://docssys.com/biservices/IServiceUpdate/CodeNamesResponse")]
        BusinessObjects.CodeName[] CodeNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Currencies", ReplyAction="http://docssys.com/biservices/IServiceUpdate/CurrenciesResponse")]
        BusinessObjects.Currency[] Currencies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Accounts", ReplyAction="http://docssys.com/biservices/IServiceUpdate/AccountsResponse")]
        BusinessObjects.Account[] Accounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Countries", ReplyAction="http://docssys.com/biservices/IServiceUpdate/CountriesResponse")]
        BusinessObjects.Country[] Countries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/DataCatalogs", ReplyAction="http://docssys.com/biservices/IServiceUpdate/DataCatalogsResponse")]
        BusinessObjects.DataCatalog[] DataCatalogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Folders", ReplyAction="http://docssys.com/biservices/IServiceUpdate/FoldersResponse")]
        BusinessObjects.Folder[] Folders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Hierarchies", ReplyAction="http://docssys.com/biservices/IServiceUpdate/HierarchiesResponse")]
        BusinessObjects.Hierarchy[] Hierarchies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Knowledges", ReplyAction="http://docssys.com/biservices/IServiceUpdate/KnowledgesResponse")]
        BusinessObjects.Knowledge[] Knowledges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Libraries", ReplyAction="http://docssys.com/biservices/IServiceUpdate/LibrariesResponse")]
        BusinessObjects.Library[] Libraries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Messages", ReplyAction="http://docssys.com/biservices/IServiceUpdate/MessagesResponse")]
        BusinessObjects.Message[] Messages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Notes", ReplyAction="http://docssys.com/biservices/IServiceUpdate/NotesResponse")]
        BusinessObjects.Note[] Notes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/PriceNames", ReplyAction="http://docssys.com/biservices/IServiceUpdate/PriceNamesResponse")]
        BusinessObjects.PriceName[] PriceNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Products", ReplyAction="http://docssys.com/biservices/IServiceUpdate/ProductsResponse")]
        BusinessObjects.Product[] Products();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Rates", ReplyAction="http://docssys.com/biservices/IServiceUpdate/RatesResponse")]
        BusinessObjects.Rate[] Rates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/StorageCells", ReplyAction="http://docssys.com/biservices/IServiceUpdate/StorageCellsResponse")]
        BusinessObjects.StorageCell[] StorageCells();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Towns", ReplyAction="http://docssys.com/biservices/IServiceUpdate/TownsResponse")]
        BusinessObjects.Town[] Towns();
        
       
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/XmlStorages", ReplyAction="http://docssys.com/biservices/IServiceUpdate/XmlStoragesResponse")]
        BusinessObjects.XmlStorage[] XmlStorages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/EntityTypes", ReplyAction="http://docssys.com/biservices/IServiceUpdate/EntityTypesResponse")]
        BusinessObjects.EntityType[] EntityTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/EntityDocuments", ReplyAction="http://docssys.com/biservices/IServiceUpdate/EntityDocumentsResponse")]
        BusinessObjects.EntityDocument[] EntityDocuments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/FactNames", ReplyAction="http://docssys.com/biservices/IServiceUpdate/FactNamesResponse")]
        BusinessObjects.FactName[] FactNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/DbObjects", ReplyAction="http://docssys.com/biservices/IServiceUpdate/DbObjectsResponse")]
        BusinessObjects.Developer.DbObject[] DbObjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/ChainKinds", ReplyAction="http://docssys.com/biservices/IServiceUpdate/ChainKindsResponse")]
        BusinessObjects.ChainKind[] ChainKinds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/Branches", ReplyAction="http://docssys.com/biservices/IServiceUpdate/BranchesResponse")]
        BusinessObjects.Branche[] Branches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docssys.com/biservices/IServiceUpdate/ResourceStrings", ReplyAction="http://docssys.com/biservices/IServiceUpdate/ResourceStringsResponse")]
        BusinessObjects.ResourceString[] ResourceStrings();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUpdateChannel : BusinessObjects.UpdateServices.ServiceUpdate.IServiceUpdate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUpdateClient : System.ServiceModel.ClientBase<BusinessObjects.UpdateServices.ServiceUpdate.IServiceUpdate>, BusinessObjects.UpdateServices.ServiceUpdate.IServiceUpdate {
        
        public ServiceUpdateClient() {
        }
        
        public ServiceUpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessObjects.CustomViewList[] CustomViewLists() {
            return base.Channel.CustomViewLists();
        }
        
        public BusinessObjects.CodeName[] CodeNames() {
            return base.Channel.CodeNames();
        }
        
        public BusinessObjects.Currency[] Currencies() {
            return base.Channel.Currencies();
        }
        
        public BusinessObjects.Account[] Accounts() {
            return base.Channel.Accounts();
        }
        
        public BusinessObjects.Country[] Countries() {
            return base.Channel.Countries();
        }
        
        public BusinessObjects.DataCatalog[] DataCatalogs() {
            return base.Channel.DataCatalogs();
        }
        
        public BusinessObjects.Folder[] Folders() {
            return base.Channel.Folders();
        }
        
        public BusinessObjects.Hierarchy[] Hierarchies() {
            return base.Channel.Hierarchies();
        }
        
        public BusinessObjects.Knowledge[] Knowledges() {
            return base.Channel.Knowledges();
        }
        
        public BusinessObjects.Library[] Libraries() {
            return base.Channel.Libraries();
        }
        
        public BusinessObjects.Message[] Messages() {
            return base.Channel.Messages();
        }
        
        public BusinessObjects.Note[] Notes() {
            return base.Channel.Notes();
        }
        
        public BusinessObjects.PriceName[] PriceNames() {
            return base.Channel.PriceNames();
        }
        
        public BusinessObjects.Product[] Products() {
            return base.Channel.Products();
        }
        
        public BusinessObjects.Rate[] Rates() {
            return base.Channel.Rates();
        }
        
        public BusinessObjects.StorageCell[] StorageCells() {
            return base.Channel.StorageCells();
        }
        
        public BusinessObjects.Town[] Towns() {
            return base.Channel.Towns();
        }
        
        
        
        public BusinessObjects.XmlStorage[] XmlStorages() {
            return base.Channel.XmlStorages();
        }
        
        public BusinessObjects.EntityType[] EntityTypes() {
            return base.Channel.EntityTypes();
        }
        
        public BusinessObjects.EntityDocument[] EntityDocuments() {
            return base.Channel.EntityDocuments();
        }
        
        public BusinessObjects.FactName[] FactNames() {
            return base.Channel.FactNames();
        }
        
        public BusinessObjects.Developer.DbObject[] DbObjects() {
            return base.Channel.DbObjects();
        }
        
        public BusinessObjects.ChainKind[] ChainKinds() {
            return base.Channel.ChainKinds();
        }
        
        public BusinessObjects.Branche[] Branches() {
            return base.Channel.Branches();
        }
        
        public BusinessObjects.ResourceString[] ResourceStrings() {
            return base.Channel.ResourceStrings();
        }
    }
}
